### ISSUE TITLE
Is there a reason to warn users about native crypto?

### ISSUE THREAD

**Issue by aarne** [webauthn-open-source/fido2-lib#109]
For some reason the library uses default console warn facility to print a message "Native crypto is enabled" without any explanation why this warning exists or if we expect users to do anything about this.

console.warn("[FIDO2-LIB] Native crypto is enabled");

can be found in at least 2 places in the codebase:
https://github.com/webauthn-open-source/fido2-lib/blob/c38c2cc762830a09331106534d63003d51884a76/lib/toolbox.js#L27
https://github.com/webauthn-open-source/fido2-lib/blob/c38c2cc762830a09331106534d63003d51884a76/lib/toolbox.js#L33

If this is needed information to the users we should improve the message to be more actionable OR we should remove the message.

**Comment by Hexagon** [comment]
+1

Native crypto works just as good as the polyfill* for fido2-lib, and native crypto is what's used under the hood most of the time (chosen automatically when running Node>=16 or Deno). The warning must be from when native crypto was experimental and incomplete.

So, i guess the warning could be removed?

PR welcome, flagging as good first issue!

(* = peculiar/webcrypto)
