### ISSUE TITLE
Is MDS3 supported?

### ISSUE THREAD

**Issue by sunday18** [webauthn-open-source/fido2-lib#116]
Hi, MDS2 is going to be deprecated this month, may I know if FIDO Metadata Service 3 is supported? If no, is there any roadmap to support MDS3?

**Comment by JamesCullum** [comment]
Yes: https://github.com/webauthn-open-source/fido2-lib/pull/71

**Comment by Hexagon** [comment]
Reopening this as Readme does no mention about supporting MDSv3. Simple fix, but just so we remember it.

**Comment by JamesCullum** [comment]
Updated
