### ISSUE TITLE
JSDOC 3 deprecation

### ISSUE THREAD

**Issue by JamesCullum** [webauthn-open-source/fido2-lib#126]
If someone has experience with JSDOC 3 to 4 migrations - we are currently using v3, which is deprecated and has a vulnerable (dev)Dependency, and would highly appreciate having someone experienced migrate it to v4.

**Comment by JamesCullum** [comment]
I created the issue after trying this and receiving dozen of errors - so its sadly not THAT easy

**Comment by Hexagon** [comment]
@JamesCullum about the problem at release, change deno,
-version from 1.20.1 to 1.x just like the test pipeline

**Comment by JamesCullum** [comment]
Thanks, done and works 👍
