### ISSUE TITLE
attestationResult suddenly return error

### ISSUE THREAD

**Issue by Faraz1995** [webauthn-open-source/fido2-lib#134]
my app was just working fine, but from yesterday , attestationResult return error as 
"typeerror: clientdata challenge was not properly encoded base64url"
first i fill my session with challenge
`ctx.session.challenge = Buffer.from(registrationOptions.challenge)`
and then in registering fingerprint i get it from session
`const challenge = new Uint8Array(ctx.session.challenge.data).buffer`
whats wrong with it?

**Comment by JamesCullum** [comment]
We did not do any changes, if that's what you mean. If you provide a full and running example including payloads, maybe someone can spot the issue you're encountering.

**Comment by Faraz1995** [comment]
yes
that was issue on my backend side
