### ISSUE TITLE
User id should be type "BufferSource", not string

### ISSUE THREAD

**Issue by segevmalool** [webauthn-open-source/fido2-lib#146]
<img width="1076" alt="image" src="https://github.com/webauthn-open-source/fido2-lib/assets/8082496/46f81bb9-5de3-4174-bc11-6273a208815c">

https://www.w3.org/TR/webauthn/#dictionary-user-credential-params
https://webidl.spec.whatwg.org/#BufferSource

Consider a code like this
```
// based on https://developer.chrome.com/blog/how-to-convert-arraybuffer-to-and-from-string/
function utf8StringToArrayBuffer (s: string) {
  const abuf = new ArrayBuffer(s.length);
  const abufView = new Uint8Array(abuf);
  for (let i = 0; i < s.length; i += 1) {
    abufView[i] = s.charCodeAt(i);
  }
  return abuf;
}

**Comment by JamesCullum** [comment]
Thanks for the suggestion - can you propose a PR that solves it and passes the tests?

**Comment by segevmalool** [comment]
Hi @JamesCullum, hope all is well! Do you think anything needs to change code wise or just a typing issue?

This PR seems to make the type error go away:

https://github.com/webauthn-open-source/fido2-lib/pull/148

**Comment by JamesCullum** [comment]
Thanks a lot, that was quick! 💯
