### ISSUE TITLE
Error: expectation did not contain value for 'userHandle'

### ISSUE THREAD

**Issue by lilac-milena** [webauthn-open-source/fido2-lib#155]
When I try to call the assertionResult function, I got the following error:
![image](https://github.com/webauthn-open-source/fido2-lib/assets/143427814/4057f400-abc2-49c4-889c-bebd3ebfcbd0)

Here's some contextual code that may be relevant to the issue:
```
const assertionExpectations = {
        // Remove the following comment if allowCredentials has been added into authnOptions so the credential received will be validate against allowCredentials array.
        // allowCredentials: [],
        // userVerification: "required",
        challenge: systemFunction.base64ToUint8Array(challenge),
        origin: "https://*",
        factor: "either",
        publicKey: logingAccount["publicKey"],
        prevCounter: logingAccount["counter"]
    };

    

    const keyDataDecoded = {
        rawId: systemFunction.base64ToArrayBuffer(keyData.rawId),
        response: {
            authenticatorData: systemFunction.base64ToArrayBuffer(keyData.response.authenticatorData),
            signature: systemFunction.base64ToArrayBuffer(keyData.response.signature),
            userHandle: systemFunction.base64ToArrayBuffer(keyData.response.userHandle),
            clientDataJSON: systemFunction.base64ToArrayBuffer(keyData.response.clientDataJSON),
        },
        id: keyData.id,
        type: keyData.type,
    }

    //console.log(keyDataDecoded)

    const authnResult = await f2l.assertionResult(keyDataDecoded, assertionExpectations);
```

```
const f2l = new Fido2Lib({
    timeout: 42000,
    rpId: "*",
    rpName: "Identity",
    // rpIcon: "https://example.com/logo.png",
    challengeSize: 128,
    attestation: "none",
    cryptoParams: [-7, -257],
    // authenticatorAttachment: "cross-platform",
    authenticatorRequireResidentKey: true,
    requireResidentKey: true,
    userVerification: "required"
    // requireResidentKey: true,
    // authenticatorUserVerification: "required"
});
```

I've checked my runtime environment, I'm using the Webauthn debugging tool for Chrome to debug, and the debugging tool shows that the "User Handle" parameter is already available
![image](https://github.com/webauthn-open-source/fido2-lib/assets/143427814/a2a9d543-ffd4-4b61-86e8-c19f5acf8f5a)
<img width="320" alt="image" src="https://github.com/webauthn-open-source/fido2-lib/assets/143427814/1151de78-409d-41a1-bfc5-edc623d0bf39">

**Comment by JamesCullum** [comment]
Is this related to your PR https://github.com/webauthn-open-source/fido2-lib/pull/154 ?

**Comment by Inzufu** [comment]
No, they're not related, it's a separate issue.

**Comment by Inzufu** [comment]
> Is this related to your PR https://github.com/webauthn-open-source/fido2-lib/pull/154 ?

No, they're not related, it's a separate issue.

**Comment by Jaepe** [comment]
In your "assertionExpectations" JSON, include the user's userHandle, which is the user's ID used at signup encoded as base64url.

**Comment by lilac-milena** [comment]
> In your "assertionExpectations" JSON, include the user's userHandle, which is the user's ID used at signup encoded as base64url.

Thank you so much for your help, it has helped me a lot, have a great day!
