### ISSUE TITLE
Regression with 3.5.1: Error: Cannot find module 'punycode.js'

### ISSUE THREAD

**Issue by pozylon** [webauthn-open-source/fido2-lib#164]
Require stack:
- /Users/xxx/Repositories/lorem/engine/node_modules/fido2-lib/dist/main.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)

**Comment by highvoltz** [comment]
I am getting the same error. Checking the packages.json, it looks like punycode.js is listed in devDependencies instead of dependencies

**Comment by Hexagon** [comment]
Oh, that's my fault, and that's correct. Punycode.js should be moved to regular dependencies. I cant fix right now, so its open for a pull request. If anyone is up for the task - bump the version one revision too.

**Comment by Hexagon** [comment]
Hopefully fixed in #165

**Comment by JamesCullum** [comment]
Should be fixed in 3.5.2 now
