### ISSUE TITLE
Attestation formats comes as "None" 

### ISSUE THREAD

**Issue by pkuntal** [webauthn-open-source/fido2-lib#18]
Hi Adam,

I am trying to receive TPM attestation statement and that's why setting attestation:"direct" in create() but still fmt in response comes as "none". How we can instruct Authenticator (Windows Hello) to use TPM as cryptographic engine.
Does none means TPM is not used for cryptographic operation?
AAGUID coming as {08987058-cadc-4b81-b6e1-30de50dcbe96} which indicates hardware authenticator.

Regards,
Pooja

**Comment by apowers313** [comment]
Have you tried this lately?

**Comment by pkuntal** [comment]
Yes I tried with Windows RS5 17713 version.

**Comment by AdamUCF** [comment]
From Microsoft's [docs](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication)...

To receive a TPM attestation statement, set attestation to "direct" when calling the create API. TPM attestation is a best effort. Only PCs with TPM 2.0 will return a TPM attestation statement, and the attestation process could fail for a variety of reasons.

**Comment by JamesCullum** [comment]
Can you test this again and provide feedback?

**Comment by Hexagon** [comment]
Bump. Adding tag "help wanted". Can anyone using Windows 11 (which most certainly have TPM 2.0 available) test this?

**Comment by JamesCullum** [comment]
I have Windows 11 with TMP 2.0, but I'm not really sure of the test case.
Do we have a demo page that we can try for this?

**Comment by Hexagon** [comment]
I'll have a look at improving https://56k.guru/webauth-debugger, so that attestation details is shown, then it will be a simple test case. :+1:

**Comment by Hexagon** [comment]
@JamesCullum Done now.

1. Go to https://56k.guru/webauthn-debugger
2. Enter a username
3. Click "Start registration"
4. Check section "Pass credentials from RP", Object -> Response -> debugAttestationObject -> fmt
5. Should be anything but "none"

With Windows 10 and Windows Hello (TPM 1.0 activated) i get "packed" for attestation, for some reason. Better than none though :)

**Comment by JamesCullum** [comment]
Thanks a lot, that's a great way to test! With Windows 11 I also get "packed" (via Windows Hello). Don't think we can currently reconstruct the issue without feedback from the issue creator, so I'd propose to close it.

**Comment by Hexagon** [comment]
Agreed 👍

**Comment by apowers313** [comment]
Do you guys have TPM 2.0 chips in your Win11 boxes? If not, you wouldn’t get the attestation.
