### ISSUE TITLE
rpIdHash validation incorrectly requires rpId to exactly match origin domain

### ISSUE THREAD

**Issue by reardencode** [webauthn-open-source/fido2-lib#21]
I believe the webauthn spec allows rpId to be a registrable suffix of the origin domain, but https://github.com/apowers313/fido2-lib/blob/master/lib/validator.js#L365 only allows it to be exactly equal to the client origin domain.

Maybe Fido2Lib options.rpId should be used here, and `rsl` might need to be checked to verify that options.rpId is a registrable suffix of clientDataJSON.origin.

**Comment by JamesCullum** [comment]
Same feature is worked on here: https://github.com/webauthn-open-source/fido2-lib/pull/52 Will close here in the meantime
