### ISSUE TITLE
authnrData rawAuthnrData should be ArrayBuffer

### ISSUE THREAD

**Issue by odensc** [webauthn-open-source/fido2-lib#23]
I'm getting an error, `authnrData rawAuthnrData should be ArrayBuffer`, when calling `assertionResult`. I passed everything required in the docs to the function.

**Comment by goldenbearkin** [comment]
Yes. me too.  Any solution or workaround?

**Comment by odensc** [comment]
Couldn't figure it out - I'm assuming there's a missing piece somewhere in the docs.

**Comment by goldenbearkin** [comment]
@apowers313 Could you help on this? 
Many thanks

**Comment by goldenbearkin** [comment]
@odensc I just made a PR, only one liner changes. Please see if it works on your side.

**Comment by Wesseldr** [comment]
It looks like assertionResult does not give this error anymore? Or is my input from a yubi key not affected by this PR?

**Comment by davedoesdev** [comment]
I've always converted it to an ArrayBuffer first but no problems once I've done that

**Comment by Wesseldr** [comment]
Hope it is picked up soon :-)

**Comment by martinord** [comment]
I actually spent many hours with the same problem. Just found the PR solves it. Hope new mainainers can merge it soon :)
