### ISSUE TITLE
Can we add attestations in u2fRootCerts.js

### ISSUE THREAD

**Issue by fgervais** [webauthn-open-source/fido2-lib#24]
I'm having discussions with a FIDO2 authenticator manufacturer to get their public attestation key.

If they allow me can I PR the addition of the key in u2fRootCerts.js?

Would that make https://webauthn.org/ able to validate the attestation?

Right now it's giving me the boring:

```
warning: {
    attesation-not-validated: "could not validate attestation because the root attestation certification could not be found",
},
```

**Comment by JamesCullum** [comment]
Webauthn.org is not maintained and linked anymore. Please contact the author of the new page for such demonstration.
