### ISSUE TITLE
In the case of localhost, this library returns an error like "origin should be https"

### ISSUE THREAD

**Issue by kg0r0** [webauthn-open-source/fido2-lib#29]
In the case of localhost, there should be no problem even if it is not https.
> Please note: both create() and get() require a Secure Context (e.g. - the server is connected by https or is the localhost), and will not be available for use if the browser is not operating in a secure context.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

I think in the case of localhost should be excluded this error.
https://github.com/apowers313/fido2-lib/blob/7341fc49479bd736b1f1b57860bcec480d1ea744/lib/utils.js#L157-L159

**Comment by mofelee** [comment]
https://github.com/apowers313/fido2-lib/pull/19

**Comment by kg0r0** [comment]
Thank you for letting me know.

**Comment by JamesCullum** [comment]
Fixed as can be seen there
