### ISSUE TITLE
authenticatorSelectionCriteria and attachment are incorrect property names.

### ISSUE THREAD

**Issue by Wesseldr** [webauthn-open-source/fido2-lib#33]
Fixed in pull request: https://github.com/apowers313/fido2-lib/pull/32

**authenticatorSelectionCriteria**
The field _authenticatorSelection_ is of type _authenticatorSelectionCriteria_ but the name should be _authenticatorSelection_ according to the [w3c: authenticatorselection](https://www.w3.org/TR/webauthn/#dom-publickeycredentialcreationoptions-authenticatorselection) Changing the property name will make the _userVerification_ working. Set the property to "required" and it enforces a PIN setup during attestation and asks for a pin during assertion. According to specs :-)
**authenticatorAttachment**
Changed property "attachment" into "authenticatorAttachment", is now also working for "platform" and "cross-platform" also tested and working now with both Solo & Yubi... well both devices are rejected when in platform mode and that is according to specs :-)
Unit tests updated

**Comment by JamesCullum** [comment]
Merged
