### ISSUE TITLE
Add support for authenticator extension

### ISSUE THREAD

**Issue by efabris** [webauthn-open-source/fido2-lib#64]
Hi @JamesCullum,

Currently the parseAuthenticatorData function [throws and error](https://github.com/webauthn-open-source/fido2-lib/blob/235973322910c057d25df6ac511a7988239a7451/lib/parser.js#L320) if the ["ED" flag is present](https://github.com/webauthn-open-source/fido2-lib/blob/235973322910c057d25df6ac511a7988239a7451/lib/parser.js#L302) in the authenticator data.

This behaviour blocks the parsing of the authenticatorData and the library fails. 

I would like to propose a different approach: it's possible to parse the extension data as reported in this [link](https://github.com/efabris/fido2-lib/blob/148eff9878b687af412f8c24e8e76ee769d50026/lib/parser.js#L331) and delegate the effective validation to a function in the validation process, as reported [here](https://github.com/efabris/fido2-lib/blob/148eff9878b687af412f8c24e8e76ee769d50026/lib/validator.js#L647). The reported validateExtensionData is very simple and in the future could be extended letting the user to provide their own function to validate extension data or could be improved to validate the most frequent extensions.

These changes allow to accept also authenticator data with extension. 

What do you think? If you agree with me I'll complete the tests and then I'll create a PR.

Enrico.

**Comment by JamesCullum** [comment]
To make sure I understand this - you mean that the server owner can configure a custom method to verify the data? If none is configured, it will be rejected or passed?

**Comment by efabris** [comment]
In a first minimal implementation the validateExtensionData check the type of the parsed extensionData. In future we could provide the custom method in the expectations, if none is provided no additional validation is executed. So if none is configured the validation is passed.

**Comment by JamesCullum** [comment]
Ok, so my understanding is correct that the programmer of the application using this library has to validate this?

Idea sounds good, a PR would be highly appreciated 👍

**Comment by efabris** [comment]
> Ok, so my understanding is correct that the programmer of the application using this library has to validate this?

Yes. I'll complete the test and i'll create the PR with the minimal implementation to add support to extension.

**Comment by efabris** [comment]
@JamesCullum, investigating more deeply the code I noticed that a mechanism to parse and validate the extensions exists. There is a procedure to register extension written by the RP programmer using this code:

```javascript
const optionGeneratorFn = (extName, type, value) => {
	console.log("optionGeneratorFn for " + extName + " during " + type);
	return value;
};
const resultParserFn = (extName, clientThing, authnrThing) => {
	console.log("resultParserFn for " + extName, clientThing, authnrThing);
};
const resultValidatorFn = () => {
	console.log("resultValidatorFn for " + extName, this.clientDataJSON, this.authnrData, this.expectations);
};

Fido2Lib.addExtension("credProtect", optionGeneratorFn, resultParserFn, resultValidatorFn);

const attestation_expectations = {...};

const f2l = new Fido2Lib({...});

f2l.enableExtension("credProtect");

const attestation_options = await f2l.attestationOptions({extensionOptions: { credProtect: 2 }});
```

This can be found in the doc of the project: [addExtension](https://webauthn-open-source.github.io/fido2-lib/Fido2Lib.html#.addExtension) and [enableExtension](https://webauthn-open-source.github.io/fido2-lib/Fido2Lib.html#enableExtension).

To test the procedure I write three simple function, but only the optionGeneratorFn is called.

I'm wondering if this mechanism could be used to implement what I suggested in my previous comments. I noticed that there are two methods in the main.js that call the functions provided by the programmer in the extension: the [parseExtensionResult ](https://github.com/webauthn-open-source/fido2-lib/blob/235973322910c057d25df6ac511a7988239a7451/lib/main.js#L603) and the [validateExtensionResult](https://github.com/webauthn-open-source/fido2-lib/blob/235973322910c057d25df6ac511a7988239a7451/lib/main.js#L618). These two function are never called in the entire project and aren't documented. I think that the static tag can be removed and we can call them in the parse and validation process for each enabled extension. In this way we can reach what I proposed previously: a simple parsing and validation is done by the addition to [parseAuthenticatorData ](https://github.com/efabris/fido2-lib/blob/148eff9878b687af412f8c24e8e76ee769d50026/lib/parser.js#L331) and by the function [validateExtensionData ](https://github.com/efabris/fido2-lib/blob/148eff9878b687af412f8c24e8e76ee769d50026/lib/validator.js#L647) that I wrote and every additional parsing or validation is demanded to the RP programmer.

What do you think?

**Comment by JamesCullum** [comment]
Sure, the more you can utilize it, the better.
Lets make sure we also document this cleanly and have an example, so that other people find this easier 👍

**Comment by Antony1060** [comment]
Any updates on this?

**Comment by efabris** [comment]
Hi Antony, in these months i had to work on other tasks. However you can use [my fork of this project](https://github.com/efabris/fido2-lib/tree/extension_support) if you need basic support for extension. Still not ready for merge but it works.

**Comment by JamesCullum** [comment]
Any progress on a PR?

**Comment by tmikaeld** [comment]
Any update on this? Is the fork still working? 

Then maybe someone with more internal knowledge can pick it up, otherwise I'll pick it up in end of the year.

**Comment by HSMDBC** [comment]
Hi, have a look at this PR: #105

**Comment by Hexagon** [comment]
@HSMDBC is this resolved by your PR, so we can close this?

**Comment by HSMDBC** [comment]
Yes, this issue can be closed. I addressed this in my PR

**Comment by Hexagon** [comment]
Great, thank you! 👍
