### ISSUE TITLE
Add support for `fmt: 'apple'`

### ISSUE THREAD

**Issue by davidthornton** [webauthn-open-source/fido2-lib#65]
Hi all,

Is it possible to mainline the Apple attestation format into this to create a sort of "commercial omnibus" canonical node library?

This might help/promote adoption?!

If you are open to external contribution and contributors -- I will definitely submit a PR for this!

Thanks,
David

**Comment by olan-a21** [comment]
Any update on this one?

**Comment by JamesCullum** [comment]
There is no PR for this yet, so feel free to create one 👍

**Comment by randomprogramming** [comment]
https://github.com/webauthn-open-source/fido2-lib/pull/87
