### ISSUE TITLE
Error: packed attestation: unknown algorithm: -257 with windows Hello

### ISSUE THREAD

**Issue by bfritscher** [webauthn-open-source/fido2-lib#69]
Library works great with chrome+ android phone as mfa, but when trying to register with windows hello I get: Error: packed attestation: unknown algorithm: -257
node_modules/fido2-lib/lib/attestations/packed.js:45:9

Is there any special configuration to setup for windows hello to work?

**Comment by wmacomber** [comment]
This is a legit question.  The library claims to be compatible with Windows Hello, but when Windows Hello is used, it uses algorithm -257 (per https://www.iana.org/assignments/cose/cose.xhtml#algorithms it lists RS256 | -257 | RSASSA-PKCS1-v1_5 using SHA-256).  fido2-lib/lib/attestations/packed.js only lists -7, -35, and -36 in its algMap variable, which causes "Error: packed attestation: unknown algorithm: -257" if you try to submit an attestation signed with that algorithm, or "DOMException: An attempt was made to use an object that is not, or is no longer, usable" if you attempt to get a Windows Hello signon without having -257 in your algorithm list.

**Comment by JamesCullum** [comment]
Any (easy) fix for this?

**Comment by 2248064246** [comment]
/node_modules/fido2-lib/lib/attestations/packed.js
```js
const algMap = new Map([
	[-7, {
		algName: "ECDSA_w_SHA256",
		hashAlg: "SHA256",
	}],
	// [-8, {
	//     name: "EdDSA",
	//     hash: undefined
	// }],
	[-35, {
		algName: "ECDSA_w_SHA384",
		hashAlg: "SHA384",
	}],
	[-36, {
		algName: "ECDSA_w_SHA512",
		hashAlg: "SHA512",
	}],
	[-257, {
		algName: 'RSASSA-PKCS1-v1_5',
		hashAlg: 'SHA256'
	}]
]);
```

> 对此有任何（简单）修复吗？

**Comment by JamesCullum** [comment]
That looks like an easy fix - can we make a test case out of it and integrate it? 

@2248064246 as you appear to have a good setup to test this, can you add this change, add a test and create a pull request?

**Comment by Hexagon** [comment]
Don't know why, but https://github.com/hexagon/webauthn-skeleton works as a charm with Windows hello (+android lock screen, +yubikey)
