### ISSUE TITLE
MDS Issues

### ISSUE THREAD

**Issue by popeeyy** [webauthn-open-source/fido2-lib#70]
I was implementing MDS according to the documentation which gives this example:
```
var mc = Fido2Lib.createMdsCollection()
// download TOC from https://mds.fidoalliance.org ...
var tocObj = await mc.addToc(tocBase64);
tocObj.entries.forEach((entry) => {
    // download entry.url ...
    mc.addEntry(entryBase64);
});
Fido2Lib.setMdsCollection(mc); // performs validation
var entry = Fido2Lib.findEntry("4e4e#4005");
```

After downloading the TOC from the provided url, I discovered that the default certificate was not valid, so I added the one provided. From there, I ran into more issues. The structure seems to be completely different than what is coded. I decoded the JWT so I could take a look for myself what the returned structure is. The library expects a hash in all of the entries, but there is no hash entry to be found. All of the data is also in a "metadataStatement" property, which I made sure to account for in my modified code. However, authenticationAlgorithm and publicKeyAlgAndEncoding are arrays and are plural in the returned data as well. They are also already strings in the arrays, which is not checked in the string conversion, making them "invalid" when they are just of an unexpected type. Then, when I tried to use findEntry it did not work with the AAGUID, which I had to convert to a hex to get. This was because the AAGUIDs in the map contained dashes, but the library tried to convert the security key's AAGUID to a base64 which matched none of the values in the map.

I am using a YubiKey 5 with NFC to test.  Am I doing something completely wrong or is there an issue with the library?

My code:
```
const cert = "CERT HERE"

axios.get("https://mds.fidoalliance.org").then(async (response) => {
    const tocObj = await mdsCollection.addToc(response.data, cert);

    tocObj.entries.forEach((entry) => {
        entry = entry.metadataStatement
        entry.authenticationAlgorithm = entry.authenticationAlgorithms[0]
        entry.publicKeyAlgAndEncoding = `ALG_KEY_${entry.publicKeyAlgAndEncodings[0].toUpperCase()}`

        mdsCollection.addEntry(base64url.encode(JSON.stringify(entry)));
    });

    Fido2Lib.addMdsCollection(mdsCollection);
})
```

To get it to work, I had to edit the library to check if the algorithms and attestationTypes were a string before attempting to convert them. I also had to create a hash for the TOC entries rather than attempting to rely on a non-existent one. Last, I had to convert all the AAGUIDs to not contain dashes so the security key's AAGUID (hex value) would match.

**Comment by JamesCullum** [comment]
I'm not aware of any design differences, but I also don't own a Yubikey 5 to check.
Do you think you can provide the changes in a testable manner, so that we can benefit from your experience?

**Comment by popeeyy** [comment]
According to the documentation, the following code should work after installing fido2-lib and axios:

```
const axios = require('axios')
const base64url = require('base64url');
const { Fido2Lib } = require("fido2-lib")

const mdsCollection = Fido2Lib.createMdsCollection("FIDO MDS 1")

const cert = "-----BEGIN CERTIFICATE-----\n" +
"MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G\n" +
"A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjMxEzARBgNVBAoTCkdsb2JhbFNp\n" +
"Z24xEzARBgNVBAMTCkdsb2JhbFNpZ24wHhcNMDkwMzE4MTAwMDAwWhcNMjkwMzE4\n" +
"MTAwMDAwWjBMMSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMzETMBEG\n" +
"A1UEChMKR2xvYmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjCCASIwDQYJKoZI\n" +
"hvcNAQEBBQADggEPADCCAQoCggEBAMwldpB5BngiFvXAg7aEyiie/QV2EcWtiHL8\n" +
"RgJDx7KKnQRfJMsuS+FggkbhUqsMgUdwbN1k0ev1LKMPgj0MK66X17YUhhB5uzsT\n" +
"gHeMCOFJ0mpiLx9e+pZo34knlTifBtc+ycsmWQ1z3rDI6SYOgxXG71uL0gRgykmm\n" +
"KPZpO/bLyCiR5Z2KYVc3rHQU3HTgOu5yLy6c+9C7v/U9AOEGM+iCK65TpjoWc4zd\n" +
"QQ4gOsC0p6Hpsk+QLjJg6VfLuQSSaGjlOCZgdbKfd/+RFO+uIEn8rUAVSNECMWEZ\n" +
"XriX7613t2Saer9fwRPvm2L7DWzgVGkWqQPabumDk3F2xmmFghcCAwEAAaNCMEAw\n" +
"DgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFI/wS3+o\n" +
"LkUkrk1Q+mOai97i3Ru8MA0GCSqGSIb3DQEBCwUAA4IBAQBLQNvAUKr+yAzv95ZU\n" +
"RUm7lgAJQayzE4aGKAczymvmdLm6AC2upArT9fHxD4q/c2dKg8dEe3jgr25sbwMp\n" +
"jjM5RcOO5LlXbKr8EpbsU8Yt5CRsuZRj+9xTaGdWPoO4zzUhw8lo/s7awlOqzJCK\n" +
"6fBdRoyV3XpYKBovHd7NADdBj+1EbddTKJd+82cEHhXXipa0095MJ6RMG3NzdvQX\n" +
"mcIfeg7jLQitChws/zyrVQ4PkX4268NXSb7hLi18YIvDQVETI53O9zJrlAGomecs\n" +
"Mx86OyXShkDOOyyGeMlhLxS67ttVb9+E7gUJTb0o2HLO02JQZR7rkpeDMdmztcpH\n" +
"WD9f\n" +
"-----END CERTIFICATE-----\n"

axios.get("https://mds.fidoalliance.org").then(async (response) => {
    const tocObj = await mdsCollection.addToc(response.data, cert);

    tocObj.entries.forEach((entry) => {
        //entry = entry.metadataStatement
        //entry.authenticationAlgorithm = entry.authenticationAlgorithms[0]
        //entry.publicKeyAlgAndEncoding = `ALG_KEY_${entry.publicKeyAlgAndEncodings[0].toUpperCase()}`

        mdsCollection.addEntry(base64url.encode(JSON.stringify(entry)));
    });

    Fido2Lib.addMdsCollection(mdsCollection);
    console.log(Fido2Lib.findMdsEntry("9c835346796b4c278898d6032f515cc5")) //Find by AAGUID provided by a key. Note: This is just a random AAGUID from the response
})
```

However, in order to get it to work, I had to install [my fork](https://github.com/popeeyy/fido2-lib/tree/metadata-fix) rather than this library and uncomment the code above. My fork is obviously just a rough fix as I tried to figure out the issue, and I am not sure if any major changes to mds.js would affect any other part of the library.

``npm i github:popeeyy/fido2-lib#metadata-fix``

I do not believe this is a problem with my YubiKey as viewing the parsed JWT response reveals a completely different format than what the library attempts to handle. It appears they may have updated this standard as there was a new document published for v3 on May 18th 2021. https://fidoalliance.org/specs/mds/fido-metadata-service-v3.0-ps-20210518.html

The new certificate was obtained from their official website. https://valid.r3.roots.globalsign.com/

**Comment by JamesCullum** [comment]
Thanks for the clarification - can we make it compatible with the previous and new format? Is there an identifier?

Did you try running your fix against the test suite?
