### ISSUE TITLE
Support for Android/iOS authenticator?

### ISSUE THREAD

**Issue by p0vidl0** [webauthn-open-source/fido2-lib#76]
Found this project as the most full FIDO2 implementation but can't make it work for Android mobile app case.

The `attestationResult` function throws the `origin was malformatted` error because the origin is not a valid web-URL and not started with https
The `clientDataJSON` is following for attestation and the same, but with `"type": "webauthn.get"` for the assert:
```json
{
    "androidPackageName": "com.example.app",
    "challenge": "CvPFgfKYZCkviLwzieQZBArgORy6ayCZ8ModjHYrl24FG_uzdSZkXEFBHpGPJ9agV9XksMeVyUkDKCg_-ZhCmOO1_JT-BAK52bjY60gSsx291Piqc30haY-Cf93levthvoQQG3YJ8yOALVS6I1VNEo23Z7vOpIXoloXauAMGN98",
    "origin": "android:apk-key-hash:-sYXRdwJA3hvue3mKpYrOZ9zSPC7b4mbgzJmdZEDO5w",
    "type": "webauthn.create",
}
```

Can some one advise, please, if it possible to configure this library or the short way to extend it to make it work?

**Comment by Hexagon** [comment]
It would be farily easy to implement this, it would just be a matter of ignoring the regular origin checks, and allowing "android:apk-key-hash:*"...

It would be nice to have some documentation on this though. Like how is this origin composed - is there more to it than android:apk-key-hash, how does the equivalent in ios look. Etc...?

**Comment by JamesCullum** [comment]
@p0vidl0 As you need it and have a test case, can you do a first version?
Or do we have another volunteer who can work on this?

**Comment by gunjanai** [comment]
I have tried multiple permutations on the possible values for origin. these are the errors I'm getting -

// if not passed origin then  Error: expectation did not contain value for 'origin'

        // origin: 'android', //code: 'ERR_INVALID_URL'

        // origin: '', // Error: expectation did not contain value for 'origin'

        // origin: "android:apk-key-hash:*************************{SHA}************", //Error: origin was malformatted

        // origin: "apk-key-hash:****************************{SHA}************", //Error: origin was malformatted

        // origin: "*******************{SHA}************", //code: 'ERR_INVALID_URL'

        // origin: "android:*******************{SHA}************", //Error: origin was malformatted

        // origin : "https://*******.glitch.me", // Error: origin was malformatted

        origin : "https://glitch.me", // Error: origin is not a valid eTLD+1

I have gone through this code for checking origin (https://github.com/webauthn-open-source/fido2-lib/blob/7598e31ff9847e89a9159d910ce026613068bde1/lib/toolbox.js#L81) but haven't found any support for android. As per my understanding the library only supports origin from web (https) but not android origins (android:apk-key-hash:)
Does anyone has any solutions on how to get origin validated in case of android?

**Comment by wparad** [comment]
@gunjanai see #121, #122

**Comment by JamesCullum** [comment]
Should be solved in newest version
