### ISSUE TITLE
AppID extension

### ISSUE THREAD

**Issue by apowers313** [webauthn-open-source/fido2-lib#8]
Add AppID extension

**Comment by apowers313** [comment]
This feature has been created, but the primary use case for the AppID extension is to migrate from U2F. Since this server doesn't support U2F, it's difficult to come up with use cases to test this. Should be revisited in the future.

**Comment by JamesCullum** [comment]
As webauthn has practically replaced u2f in practical usage, I believe this won't be needed anymore.
