### ISSUE TITLE
Cannot upgrade pkijs past 2.1.60

### ISSUE THREAD

**Issue by Hexagon** [webauthn-open-source/fido2-lib#86]
Cannot figure this one out...

All is ok with pkijs@2.1.60 - Error with pkijs@2.1.61

```bash
    verifyCertChain ...
      rejects on empty arguments ... ok (13ms)
      works for MDS2 ... FAILED (93ms)
        Error: No revocation values found for one of certificates: No valid CRLs found
                                throw new Error(res.resultMessage);
                                      ^
            at Function.verifyCertChain (/fido2-lib/lib/certUtils.js:587:10)
```
Failing test: 
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/test/certUtils.test.js#L531

Related certs available here:
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/test/helpers/fido2-helpers.js#L4598

Failing line:
https://github.com/webauthn-open-source/fido2-lib/blob/e60117e18244c4cf9420d026b957a55d17e71d5a/lib/certUtils.js#L587

Could it be related to this change in CertificateChainValidationEngine.js? Or something else?

![image](https://user-images.githubusercontent.com/419737/168173274-b5f66245-373e-4287-92f3-d305d9046b9d.png)

**Comment by JamesCullum** [comment]
MDS v2 is deprecated - maybe it was turned off and CRLs were taken down?

**Comment by Hexagon** [comment]
Oh, there it is. If i "turn back time" the tests pass with latest version of pkijs. The failing tests needs to be disabled as they use expired certs and crls.
