### ISSUE TITLE
Authenticating from multiple devices

### ISSUE THREAD

**Issue by randomprogramming** [webauthn-open-source/fido2-lib#97]
I am having trouble in understanding how exactly one would authenticate a user that wants to use multiple devices to log in.. Lets say a user has a mac laptop with touchId and a windows pc with a security key. I register on my laptop using my touch id. That generates a public key which is then saved, and I can log in just fine on my laptop. Now I switch to my PC and want to register. I understand that there is a `allowCredentials` field, but I am not sure what is its use exactly. If I try to register on my PC, and save just the credential ID of that pc, but I try to log in using the public key generated from the laptop, I am guessing that will just fail, right? Would I need to also save an array of public keys, and try to authenticate with each one of them? Or maybe save which credential ID matches to which public key? This is just theory crafting as I unfortunately don't have multiple webauth capable devices around me to test right now, so sorry if this may be a dumb question

**Comment by JamesCullum** [comment]
FIDO2 uses a key generated on the device (in case of new iOS, it will be synced across devices in the future). This means that if you try to sign in from a different device, the authentication will fail.

AllowCredentials is just helping the client pick the right key for this specific website and authentication (eg multiple users registered). By telling the client which key you expect to receive, the device can provide a fitting one or clarify, that the current device is not registered and fail right away.

Yes, from a workflow you ask the user to register their device, save the public key of the registered device and provide this during login in `allowCredentials` - the client will then use this key to sign the request and send it back.

You will be surprised to hear that both Windows, iOS and Android devices are FIDO2 compatible nowadays (browser support may vary), so its likely you do have a test device at hand.

**Comment by randomprogramming** [comment]
Okay I found a chrome extension which can simulate security keys so I will start testing out with that, but I am not quite sure what you mean by `save the public key of the registered device and provide this during login in allowCredentials`. 

So allowCredentials expects an (array of) Id, type and transports. The ID is the credential ID if I'm not mistaken. The type I understand how to get, but the transports seem to always be undefined after calling `attestationResult`, unless I'm doing something wrong.. And where would you pass the public key then?

Also another questions, will the same security device(say touch sensor) always generate the same credential ID?

**Comment by JamesCullum** [comment]
Sounds like maybe theres your confusion: Registration and Login are two different, distinct steps. If you want to add FIDO to your account, you need to already be signed in and add your device as 2nd factor, registering it. During login, the server can challenge you by asking you to reuse the same key to sign a statement, proving that its the same device as before.

Generally the client provides you with all data you need to ask it later on. Try leaving out fields you dont have input for, and see if it works.

No, FIDO is designed with privacy built in. Every time you register, it creates a new pair of credentials.

**Comment by randomprogramming** [comment]
No I understand that.. But I have already implemented a system to register/login using only webauthn like the example at https://webauthn.io

Now let's say I want to login into the same account from a different device into that site.. I will again have to go through the process of registering that device(authenticator), and that will generate a new public key. But the user already has a public key saved from my first device that I registered with, and I won't be able login from the second device with that public key.. My idea was to save all the public keys generated by one user, and then try calling `assertionResult` once for each of those public keys, since it only accepts one at a time, is that a valid idea?

**Comment by Hexagon** [comment]
@randomprogramming Check out https://56k.guru/webauthn for a minimal demo supporting this

**Comment by randomprogramming** [comment]
Yep, that's what I thought I need to do, although I didn't know that the cred Id would also need to be saved in the DB. Thank you for the demo, helped a lot
